from .color import ColorMode
from .ansi import AnsiString

class Drawer:
    plane: list[AnsiString]
    def __init__(self, size: tuple[int, int], plane_color: tuple[int, int, int]) -> None: ...
    def render(self, mode: ColorMode) -> str: ...
    def __str__(self) -> str: ...
    def place(self, astr: AnsiString, pos: tuple[int, int], assign: bool) -> None: ...
    def center_place(self, astr: AnsiString, ypos: int, assign: bool) -> None: ...
    def place_str(self, str: str, pos: tuple[int, int]) -> None: ...
    def center_place_str(self, str: str, ypos: int) -> None: ...
    def place_drawer(self, other: 'Drawer', pos: tuple[int, int], border: bool) -> None: ...