from datetime import timedelta

from .color import ColorMode, AnsiColor
from .ansi import AnsiString


class DrawerFast:
    def __init__(self, width: int, height: int, plane_color: AnsiColor | None = None) -> None: ...
    def fill(self, color: AnsiColor): ...
    def render(self, mode: ColorMode) -> str: ...
    def text(self, text: str, posx: int, posy: int, fore_color: AnsiColor | None = None, back_color: AnsiColor | None = None) -> None: ...
    def text_colored(self, text: AnsiString, posx: int, posy: int) -> None: ...
    def text_centered(self, text: str, posy: int, fore_color: AnsiColor | None = None, back_color: AnsiColor | None = None) -> None: ...
    def text_colored_centered(self, text: AnsiString, posy: int) -> None: ...
    def rect(self, posx: int, posy: int, width: int, height: int, border_color: AnsiColor, fill_color: AnsiColor | None = None) -> None: ...
    def get_plane(self) -> 'Plane': ...
    def place_drawer(self, drawer: 'DrawerFast', posx: int, posy: int) -> None: ...
    def place_plane(self, plane: 'Plane', posx: int, posy: int) -> None: ...

class Plane:
    def __init__(self, width: int, height: int, plane_color: AnsiColor | None = None) -> None: ...

def test_render() -> str: ...
def render_benchmark() -> timedelta: ...