from .color import ColorMode, AnsiColor

# this ugly, but I can't do nothing about it
class AnsiGraphicMode:
    BOLD = ...
    FAINT = ...
    ITALIC = ...
    UNDERLINE = ...
    BLINKING = ...
    REVERSE = ...
    HIDDEN = ...
    STRIKE = ...

class AnsiGraphics:
    mode: int
    def __init__(self) -> None: ...
    @staticmethod
    def to_string(reset: bool) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: 'AnsiGraphics') -> bool: ...
    def _from_bits(self, bits: int) -> 'AnsiGraphics': ...


class AnsiChar:
    char: str
    back_color: AnsiColor
    fore_color: AnsiColor
    graphics: AnsiGraphics
    def __init__(self, char: str, fore: tuple[int, int, int] = None, back: tuple[int, int, int] = None) -> None: ...
    def to_string(self, mode: ColorMode) -> str: ...
    def __str__(self) -> str: ...
    def set(self, c: str) -> None: ...
    def as_ansistring(self) -> AnsiString: ...
    def __add__(self, other: 'AnsiChar') -> AnsiString: ...

class AnsiString:
    vec: list[AnsiChar]
    def __init__(self, str: str, fore: tuple[int, int, int] = None, back: tuple[int, int, int] = None) -> None: ...
    def to_string(self, mode: ColorMode) -> str: ...
    def split_at(self, mid: int) -> tuple[AnsiString, AnsiString]: ...
    def add_graphics(self, agm: AnsiGraphics) -> None: ...
    def __add__(self, other: 'AnsiString') -> 'AnsiString': ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: 'AnsiString') -> bool: ...