class ColorMode:
    Limited = ...
    TrueColor = ...

class ColorGround:
    Back = ...
    Fore = ...

class AnsiColor:
    def __init__(self, r: int, g: int, b: int) -> None: ...
    def to_string(self, mode: ColorMode, ground: ColorGround) -> str: ...